In [1]:
import warnings
import subprocess
import os
from selenium import webdriver
import time
from fast_reports import FastReports


start = time.time()

warnings.filterwarnings('ignore')

fr = FastReports()
fr.download_tasks()

fr.backlogsub()
fr.specsub()
fr.changesub()

fr.download_master_2()

fr.quarter='2Q23'
fr.delivery_report()
fr.validsub()

fr.dev_over90()
fr.chg_over30()

fr.download_ideas_sd()
fr.ideas()

if os.path.exists(r'C:\Users\016434613\Desktop\Specification.xlsx'):
    fr.update_specification()
    fr.add_days()
else:
    if os.path.exists(r'C:\Users\016434613\Desktop\Reports\Specification.xlsx'):
        fr.filepath_spec = r'C:\Users\016434613\Desktop\Reports\Specification.xlsx'
        fr.update_specification()
        fr.add_days()
    else:
        print('Specification file does not exist!')

end = time.time()
mins = (end-start)/60.00
if mins < 1:
    mins = end-start
    print('Reports created/updated in: {:.2f} seconds'.format(mins))
else:
    print('Reports created/updated in: {:.2f} minutes'.format(mins))

Reports created/updated in: 5.12 minutes

In [1]:
import warnings
import subprocess
import os
from selenium import webdriver
import time
from fast_reports import FastReports


start = time.time()

warnings.filterwarnings('ignore')

fr = FastReports()
fr.quarter='2Q23'
fr.delivery_report()

end = time.time()
mins = (end-start)/60.00
if mins < 1:
    mins = end-start
    print('Reports created/updated in: {:.2f} seconds'.format(mins))
else:
    print('Reports created/updated in: {:.2f} minutes'.format(mins))

Reports created/updated in: 9.81 seconds

In [5]:
import pandas as pd
import re
import subprocess
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import os
import requests
import json
import time
import pickle
import glob
from shutil import copyfile

filepath_ = r"C:\Users\016434613\Desktop\Delivery Report.xlsx"


df = pd.read_excel(filepath_,sheet_name="Sheet1")
df_ = df.loc[df['Developer']=="x"]
df_

,Manager,Developer,Count,SAVING HS,QUARTER,ROBOT_NUMBER,TITLE,STATUS,UPLOAD DATA SYSTEMS,REGIONS
3,NaN,x,1,13.4,2Q23,ATA833,AR Collection and Recovery - iERP,In Production,SAP YPE,AP
5,NaN,x,1,45.0,2Q23,ATA255,GDPAIP Consolidation journal AM,In Production,CGLUI,AMERICAS
7,NaN,x,1,950.0,2Q23,ATA807,QTM MLN Activities CLS,In Production,GLUI,"AMERICAS, AP, EMEA"
8,NaN,x,1,6.0,2Q23,ATA789,Kobe Steel Rebate Segmentation,In Production,CGLUI,AMERICAS
11,NaN,x,1,38.0,2Q23,RPA003,Progress Master Report Download,In Production,None,"AMERICAS, AP, EMEA, JP"
12,NaN,x,1,24.0,2Q23,ATA824,COF Settlements to IBM,In Production,GLUI,AMERICAS
20,NaN,x,1,60.0,2Q23,ATA835,QTM Accounts Payable Details TPS iERP,In Production,SAP YPE,"AMERICAS, EMEA"
22,NaN,x,1,60.0,2Q23,ATA834,QTM Accounts Payable Details TPS GLUI,In Production,GLUI,"AMERICAS, EMEA"
26,NaN,x,1,430.0,2Q23,ATA811,QTM MLN Activities iERP,In Production,SAP YPE,"AMERICAS, AP, EMEA"
27,NaN,x,1,1.0,2Q23,RPA000,Consolidation GLUI - Processes & Objects,In Production,CGLUI,"AMERICAS, AP, EMEA, JP"
30,NaN,x,1,3.0,2Q23,RPA004,Hyperion Maintenance Close Out,In Production,CGLUI,AMERICAS
32,NaN,x,1,50.0,2Q23,RPA006,Workiva SEC BOX logs,In Production,None,EMEA
33,NaN,x,1,50.0,2Q23,RPA007,BOX Event Logs Export IBM RPA,In Production,None,"AMERICAS, AP, EMEA, JP"
34,NaN,x,1,58.0,2Q23,ATA845,DUE IBM SETTLEMENT - iERP - CUF,In Production,SAP YPE,EMEA
35,NaN,x,1,126.0,2Q23,RPA010,BLB Unbilled Segmentation,In Production,CGLUI,EMEA

In [8]:
filepath_ = r"C:\Users\016434613\Downloads\progress_dt_tasks_details_report.xlsx"
quarter = "2Q23"

df = pd.read_excel(filepath_,sheet_name="Tasks")
df = df.rename(columns={'ROBOT NUMBER':'ROBOT_NUMBER'})

df_lindo = df.loc[:,['ORIGIN RELEASE','STATUS','ROBOT_NUMBER','TITLE','UPLOAD DATA SYSTEMS','REGIONS','MANUAL EXECUTION DURATION (hours per year)','CURRENT VERSION ID']]
df_lindo = df_lindo.rename(columns={'MANUAL EXECUTION DURATION (hours per year)':'SAVING HS','CURRENT VERSION ID':'VERSION ID'})

df4 = df_lindo
df4['ORIGIN RELEASE'] = df4['ORIGIN RELEASE'].apply(lambda x: str(x))
df4['QUARTER'] = df4['ORIGIN RELEASE'].apply(lambda x: x[0:4]+x[5:7])

df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '1Q21' if x == '202103' else '1Q21' if x == '202102' else '1Q21' if x == '202101' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '2Q21' if x == '202106' else '2Q21' if x == '202105' else '2Q21' if x == '202104' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '3Q21' if x == '202109' else '3Q21' if x == '202108' else '3Q21' if x == '202107' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '4Q21' if x == '202112' else '4Q21' if x == '202111' else '4Q21' if x == '202110' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '1Q22' if x == '202201' else '1Q22' if x == '202202' else '1Q22' if x == '202203' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '2Q22' if x == '202206' else '2Q22' if x == '202205' else '2Q22' if x == '202204' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '3Q22' if x == '202209' else '3Q22' if x == '202208' else '3Q22' if x == '202207' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '4Q22' if x == '202212' else '4Q22' if x == '202211' else '4Q22' if x == '202210' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '1Q23' if x == '202303' else '1Q23' if x == '202302' else '1Q23' if x == '202301' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '2Q23' if x == '202306' else '2Q23' if x == '202305' else '2Q23' if x == '202304' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '3Q23' if x == '202309' else '3Q23' if x == '202308' else '3Q23' if x == '202307' else x)
df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '4Q23' if x == '202312' else '4Q23' if x == '202311' else '4Q23' if x == '202310' else x)



df5 = df4.loc[df4['QUARTER']==quarter,]
df5.drop(columns=["ORIGIN RELEASE"],inplace=True)
df5.to_excel(r"C:\Users\016434613\Desktop\test versions.xlsx", index=False)
print("done")

done

## Backlog Only:

In [5]:
    filepath_ = self.filepath_master

    df_Development = pd.read_excel(filepath_,sheet_name="Development (Iterations)")

    df_Development = df_Development.loc[:,['VERSION ID','DEVELOPERS']]
    df_Development.drop_duplicates('VERSION ID',inplace=True)

    df_Development.reset_index(inplace=True, drop=True)

    df5 = df5.merge(df_Development, on="VERSION ID", how="left")

    df5.loc[df5['VERSION ID']=='6329f38e3d3f2f2ee3ebc99e','DEVELOPERS']='Dario Cesar Atach'
    df5.loc[df5['VERSION ID']=='633549dbaec8d48dde23dff8','DEVELOPERS']='Marián Chrást'
    df5.loc[df5['VERSION ID']=='633823c7ffd0c408ad843990','DEVELOPERS']='Branislav Podoba'
    df5.loc[df5['ROBOT_NUMBER']=='ATA053','DEVELOPERS']='Milan Babčanec'
    df5.loc[df5['ROBOT_NUMBER']=='ATA712','DEVELOPERS']='Richard Hantke'
    df5.loc[df5['ROBOT_NUMBER']=='WBA012','DEVELOPERS']='Rodrigo Maximiliano Cremella'

    df5['DEVELOPERS'] = df5['DEVELOPERS'].fillna(value='x')

    pos = []
    valor = []
    cont=0

    for i in range(df5['DEVELOPERS'].size):
        x=re.search(",",df5['DEVELOPERS'][i])
        if x is not None:
            valor.append(df5['DEVELOPERS'][i])
            Devel = valor[cont].split(",")
            df5['DEVELOPERS'][i]=Devel[0]
            pos.append(i)
            cont+=1

    df10 = self.mgr_report()

    df5 = df5.merge(df10, on="DEVELOPERS", how="left")

    for t in range(len(pos)):
        df5['DEVELOPERS'][pos[t]]=valor[t]

    df5.loc[df5['DEVELOPERS']=="Andre Daniel Rodrigues",'Manager']="Andrej Csiaki"
    df5.loc[df5['DEVELOPERS']=="Martin Nicolas Benitez Alegre",'Manager']="Martin Campos"
    df5.loc[df5['DEVELOPERS']=="Tomas Funes",'Manager']="Martin Campos"
    df5.loc[df5['ROBOT_NUMBER']=="ODA139",'DEVELOPERS']="Ezequiel Ferlauto"
    df5.loc[df5['ROBOT_NUMBER']=="ODA149",'DEVELOPERS']="Ezequiel Ferlauto"
    df5.loc[df5['ROBOT_NUMBER']=="ODA146",'DEVELOPERS']="Ezequiel Ferlauto"
    df5.loc[df5['ROBOT_NUMBER']=="ODA147",'DEVELOPERS']="Ezequiel Ferlauto"
    df5.loc[df5['ROBOT_NUMBER']=="ODA144",'DEVELOPERS']="Ezequiel Ferlauto"
    df5.loc[df5['ROBOT_NUMBER']=="ODA128",'DEVELOPERS']="Ezequiel Ferlauto"
    df5.loc[df5['ROBOT_NUMBER']=="ODA140",'DEVELOPERS']="Ezequiel Ferlauto"
    df5.loc[df5['ROBOT_NUMBER']=="ODA190",'DEVELOPERS']="Ezequiel Ferlauto"
    df5.loc[df5['ROBOT_NUMBER']=="ODA137",'DEVELOPERS']="Ezequiel Ferlauto"
    df5.loc[df5['ROBOT_NUMBER']=="ODA143",'DEVELOPERS']="Bruno Secchiari"
    df5.loc[df5['ROBOT_NUMBER']=="ODA111",'DEVELOPERS']="Bruno Secchiari"
    df5.loc[df5['ROBOT_NUMBER']=="ODA178",'DEVELOPERS']="Bruno Secchiari"
    df5.loc[df5['ROBOT_NUMBER']=="ODA186",'DEVELOPERS']="Bruno Secchiari"
    df5.loc[df5['ROBOT_NUMBER']=="ODA181",'DEVELOPERS']="Bruno Secchiari"
    df5.loc[df5['ROBOT_NUMBER']=="ODA169",'DEVELOPERS']="Bruno Secchiari"
    df5.loc[df5['ROBOT_NUMBER']=="ODA182",'DEVELOPERS']="Bruno Secchiari"
    df5.loc[df5['ROBOT_NUMBER']=="ODA175",'DEVELOPERS']="Peter Blahut"
    df5.loc[df5['ROBOT_NUMBER']=="ODA184",'DEVELOPERS']="Peter Blahut"
    df5.loc[df5['ROBOT_NUMBER']=="ODA185",'DEVELOPERS']="Peter Blahut"
    df5.loc[df5['ROBOT_NUMBER']=="ODA193",'DEVELOPERS']="Peter Blahut"
    df5.loc[df5['ROBOT_NUMBER']=="ODA194",'DEVELOPERS']="Peter Blahut"

    df5.loc[df5['DEVELOPERS']=="Michal Bezák",'Manager']="Andrej Csiaki"

    df5['Count']=1

    df5 = df5.loc[:,['Manager','DEVELOPERS','Count','SAVING HS','QUARTER','ROBOT_NUMBER','TITLE','STATUS','UPLOAD DATA SYSTEMS','REGIONS']]
    df5 = df5.rename(columns={'DEVELOPERS':'Developer'})
    df5.to_excel(r"C:\Users\016434613\Desktop\Delivery Report.xlsx", index=False)

Report successfully created!

### Older Version of Delivery Report:

In [ ]:
    df = pd.read_excel(filepath_,sheet_name="DT Tasks")
df = df.rename(columns={'ROBOT NUMBER':'ROBOT_NUMBER'})

df_lindo = df.loc[:,['ORIGIN RELEASE','STATUS','ROBOT_NUMBER','TITLE','AUTOMATION TYPE','REGIONS','MANUAL EXECUTION DURATION (hours per year)']]
df_lindo = df_lindo.rename(columns={'MANUAL EXECUTION DURATION (hours per year)':'SAVING HS'})

df_ATA = pd.read_excel(r"C:\Users\016434613\Box\ATA Other\ATA-ODA-WBA-RPA number assigment.xlsx",sheet_name="ATA")
df_ATA = df_ATA.rename(columns={'Task #':'ROBOT_NUMBER'})


df3 = df_lindo
df_ATA_2 = df_ATA.loc[:,['ROBOT_NUMBER','Developer']]

df4 = df3.merge(df_ATA_2, on="ROBOT_NUMBER", how="left")
df4['ORIGIN RELEASE'] = df4['ORIGIN RELEASE'].apply(lambda x: str(x))
df4['QUARTER'] = df4['ORIGIN RELEASE'].apply(lambda x: x[4:7]+x[11:15])

df4['QUARTER'] = df4['QUARTER'].apply(lambda x: '1Q' if x == 'Jan2022' else '1Q' if x == 'Feb2022' else '1Q' if x == 'Mar2022' else 'Other')

df5 = df4.loc[df4['QUARTER']=='1Q',]
df5.drop(columns=["ORIGIN RELEASE"],inplace=True)


df_ODA = pd.read_excel(r"C:\Users\016434613\Box\ATA Other\ATA-ODA-WBA-RPA number assigment.xlsx",sheet_name="ODA")
df_ODA = df_ODA.rename(columns={'Task #':'ROBOT_NUMBER'})
df_ODA = df_ODA.loc[:,['ROBOT_NUMBER','Developer']]
df5 = df5.merge(df_ODA, on="ROBOT_NUMBER", how="left")

df5['Developer'] = df5.apply(lambda x: x['Developer_x'] if str(x['Developer_y'])=="nan" else x['Developer_y'],axis=1)
df5.drop(columns=['Developer_y','Developer_x'],inplace=True)



mgrserials = ['016434613','A01130693','A51733693','900688897']
mgrname = {'016434613':'Martin Campos','A01130693':'Marek Tarkos','A51733693':'Andrej Csiaki','900688897':'Melissa Bledsoe'}
devnames = {}
for mgr in mgrserials:
    request = req.urlopen("https://unified-profile-api.us-south-k8s.intranet.ibm.com/v3/profiles/" + mgr + "/teamResolved")
    datos = request.read().decode()
    dictdatos = json.loads(datos)
    devlist = dictdatos['content']['functional']['reports']
    for dev in devlist:
        #method setdefault(key,[]) sirve para poner una primera key con una lista vacia, si no, tira error de que no existe la key
        devnames.setdefault(mgrname[mgr], []).append(dev['nameDisplay'])
        
### Create Lists ###
devlistmc = devnames['Martin Campos']
devlistmt = devnames['Marek Tarkos']
devlistac = devnames['Andrej Csiaki']
devlistmb = devnames['Melissa Bledsoe']

### Create 2 dimension df, 1 column with the list, second column value fixed de Mgr ###
df6 = pd.DataFrame(devlistmc, columns=['Developer'])
df6.loc[df6['Developer']=="Pablo (Paul) Iacovone",'Developer']="Pablo Iacovone"
df6.loc[df6['Developer']=="Santiago Akira Kitashima",'Developer']="Santiago Kitashima"
df6.loc[df6['Developer']=="Ezequiel Ricardo Ferlauto",'Developer']="Ezequiel Ferlauto"
df6.loc[df6['Developer']=="Andrés Lopez Grosman",'Developer']="Andres Grosman"
df6.loc[df6['Developer']=="Dario Cesar Atach",'Developer']="Dario Atach"
df6['Manager'] = "Martin Campos"

df7 = pd.DataFrame(devlistmt, columns=['Developer'])
df7.loc[df7['Developer']=="Viera Babčancová",'Developer']="Viera Babcancova"
df7.loc[df7['Developer']=="Milan Babčanec",'Developer']="Milan Babcanec"
df7.loc[df7['Developer']=="Adam Balák",'Developer']="Adam Balak"
df7.loc[df7['Developer']=="Peter Blahut",'Developer']="Peter Blahut"
df7.loc[df7['Developer']=="Viera Csiaki",'Developer']="Viera Csiaki"
df7.loc[df7['Developer']=="Barbora Depešová",'Developer']="Barbora Depesova"
df7.loc[df7['Developer']=="Richard Hantke",'Developer']="Richard Hantke"
df7.loc[df7['Developer']=="Lenka Holáňová",'Developer']="Lenka Holanova"
df7.loc[df7['Developer']=="Andrea Hrčková",'Developer']="Andrea Hrckova"
df7.loc[df7['Developer']=="Miroslav Kocian",'Developer']="Miroslav Kocian"
df7.loc[df7['Developer']=="Kristína Margetinová",'Developer']="Kristina Margetinova"
df7.loc[df7['Developer']=="Lucia Mikuš",'Developer']="Lucia Mikus"
df7.loc[df7['Developer']=="Soňa Olšová",'Developer']="Sona Olsova"
df7.loc[df7['Developer']=="Marta Pancotti",'Developer']="Marta Pancotti"
df7.loc[df7['Developer']=="Nina Tadlánková",'Developer']="Nina Tadlankova"
df7.loc[df7['Developer']=="Ivan Trubač",'Developer']="Ivan Trubac"
df7.loc[df7['Developer']=="Kristína Vojtová",'Developer']="Kristina Vojtova"
df7.loc[df7['Developer']=="Lubomir Cmiko (Lubo)",'Developer']="Lubomir Cmiko"
df7.loc[df7['Developer']=="Radomíra Šulová",'Developer']="Radomira Sulova"
df7['Manager'] = "Marek Tarkos"

df8 = pd.DataFrame(devlistac, columns=['Developer'])
df8.loc[df8['Developer']=="Marián Chrást",'Developer']="Marian Chrast"
df8.loc[df8['Developer']=="Massimo Cireddu",'Developer']="Massimo Cireddu"
df8.loc[df8['Developer']=="Katarina Kadlecova",'Developer']="Katarina Kadlecova"
df8.loc[df8['Developer']=="Marta Kapolková",'Developer']="Marta Kapolkova"
df8.loc[df8['Developer']=="Nikolaj Kniha",'Developer']="Nikolaj Kniha"
df8.loc[df8['Developer']=="Veronika Krchnáková",'Developer']="Veronika Krchnakova"
df8.loc[df8['Developer']=="Michele Lobina",'Developer']="Michele Lobina"
df8.loc[df8['Developer']=="Vladimír Maťo",'Developer']="Vladimir Mato"
df8.loc[df8['Developer']=="Veronika Miklovičová",'Developer']="Veronika Miklovicova"
df8.loc[df8['Developer']=="Richard Nerodolík",'Developer']="Richard Nerodolik"
df8.loc[df8['Developer']=="Micheál O'Reilly",'Developer']="Mícheál O'Reilly"
df8.loc[df8['Developer']=="Michala Ožóg",'Developer']="Michala Ozog"
df8.loc[df8['Developer']=="Branislav Podoba",'Developer']="Branislav Podoba"
df8.loc[df8['Developer']=="Andre Daniel Rodrigues",'Developer']="Andre Rodrigues"
df8.loc[df8['Developer']=="Terézia Straková",'Developer']="Terezia Strakova"
df8.loc[df8['Developer']=="Lenka Tarkošová",'Developer']="Lenka Tarkosova"
df8.loc[df8['Developer']=="Valentína Vargová",'Developer']="Valentina Vargova"
df8.loc[df8['Developer']=="Marek Štípala",'Developer']="Marek Stipala"
df8['Manager'] = "Andrej Csiaki"

df9 = pd.DataFrame(devlistmb, columns=['Developer'])
df9.loc[df9['Developer']=="Gabe Hutson",'Developer']="Gabriel Hutson"
df9['Manager'] = "Melissa Bledsoe"


### Append results into one df - df10 ####
df10 = df6
df10 = df10.append(df7)
df10 = df10.append(df8)
df10 = df10.append(df9)

#pos = []
#valor = []
#cont=0

#for i in range(df5['Developer'].size):
#    x=re.search(",",df5['Developer'][i])
#    if x is not None:
#        valor.append(df5['Developer'][i])
#        Devel = valor[cont].split(",")
#        df5['Developer'][i]=Devel[0]
#        pos.append(i)
#        cont+=1

#df5 = df5.merge(df10, on="Developer", how="left")
#df5.loc[df5["ROBOT_NUMBER"]=="ODA112","Developer"]="Bruno Secchiari"
#df5.loc[df5["ROBOT_NUMBER"]=="ODA127","Developer"]="Bruno Secchiari"
#for t in range(len(pos)):
#    df5['Developer'][pos[t]]=valor[t]
    
#df5['Count']=1
        
#df5 = df5.loc[:,['Manager','Developer','Count','SAVING HS','QUARTER','ROBOT_NUMBER','TITLE','STATUS','AUTOMATION TYPE','REGIONS']]
#df5.to_excel(r"C:\Users\016434613\Desktop\Delivery Report.xlsx", index=False)

In [5]:

    df_Development = pd.read_excel(filepath_,sheet_name="Development (Iterations)")

    df_Development = df_Development.loc[:,['VERSION ID','STATUS','DEVELOPERS','STARTED','COMPLETED']]
    df_Development = df_Development.loc[df_Development['STATUS']!="Discarded"]
    df_Development = df_Development.loc[df_Development['STATUS']!="Sunset"]
    df_Development = df_Development.loc[df_Development['STATUS']!="Closed"]
    df_Development = df_Development.loc[df_Development['STATUS']!="In Production"]

    df_Development['STARTED'] = df_Development['STARTED'].apply(lambda x: str(x))
    df_Development['STARTED'] = df_Development['STARTED'].apply(lambda x: x[8:10]+"/"+x[4:7]+"/"+x[11:15])

    df_Development = df_Development.loc[:,['VERSION ID','DEVELOPERS','STARTED']]

    df_Development.fillna(value="?",inplace=True)

    df_Development.reset_index(inplace=True, drop=True)

    for i in range(df_Development['STARTED'].size):
        x = df_Development['STARTED'][i]
        m = x[3:6]
        s = x[0:3]+months[m]+x[6:12]
        df_Development['STARTED'][i]=s


    df_Merge = df_Versions.merge(df_Development, on="VERSION ID", how="left")
    #df_Merge.drop(columns=['index_x','index_y'],inplace=True)
    df_Merge.dropna(inplace=True)

    df_Merge.reset_index(inplace=True, drop=True)
    #df_Merge.drop(columns=['index'],inplace=True)

    from datetime import datetime
    p = datetime.today().strftime('%d/%m/%Y')
    t = datetime.strptime(p, '%d/%m/%Y')

    valor = []
    for i in range(df_Merge['STARTED'].size):
        d1 = datetime.strptime(df_Merge['STARTED'][i],'%d/%m/%Y')
        dif = t - d1
        difD = dif.days
        valor.append(difD)

    df_Merge['DAYS']=valor
    df_Merge = df_Merge.loc[df_Merge['DAYS']>90]
    df_Merge.drop_duplicates('VERSION ID', inplace=True)

    df_Merge.reset_index(inplace=True, drop=True)

    df10 = mgr_report()

    pos = []
    valor = []
    cont=0

    #df_Merge['DEVELOPERS']
    for i in range(df_Merge['DEVELOPERS'].size):
        x=re.search(",",df_Merge['DEVELOPERS'][i])
        if x is not None:
            valor.append(df_Merge['DEVELOPERS'][i])
            Devel = valor[cont].split(",")
            df_Merge['DEVELOPERS'][i]=Devel[0]
            pos.append(i)
            cont+=1

    df_Merge = df_Merge.merge(df10, on="DEVELOPERS", how="left")

    for t in range(len(pos)):
        df_Merge['DEVELOPERS'][pos[t]]=valor[t]

    df_Merge['Count']=1
    df_Merge.loc[df_Merge['DEVELOPERS']=="Tomas Funes",'Manager']="Martin Campos"
    df_Merge.loc[df_Merge['DEVELOPERS']=="Andre Daniel Rodrigues",'Manager']="Andrej Csiaki"
    df_Merge.loc[df_Merge['ROBOT NUMBER']=="ODA128",'DEVELOPERS']="Ezequiel Ferlauto"
    df_Merge.loc[df_Merge['ROBOT NUMBER']=="ODA111",'DEVELOPERS']="Bruno Secchiari"
    df_Merge.loc[df_Merge['ROBOT NUMBER']=="ODA140",'DEVELOPERS']="Ezequiel Ferlauto"
    df_Merge.loc[df_Merge['ROBOT NUMBER']=="ODA137",'DEVELOPERS']="Ezequiel Ferlauto"
    df_Merge.loc[df_Merge['ROBOT NUMBER']=="ODA146",'DEVELOPERS']="Ezequiel Ferlauto"
    df_Merge.loc[df_Merge['ROBOT NUMBER']=="ODA135",'DEVELOPERS']="Ezequiel Ferlauto"
    df_Merge.loc[df_Merge['ROBOT NUMBER']=="ODA147",'DEVELOPERS']="Ezequiel Ferlauto"
    df_Merge.loc[df_Merge['ROBOT NUMBER']=="ODA144",'DEVELOPERS']="Ezequiel Ferlauto"
    df_Merge.loc[df_Merge['ROBOT NUMBER']=="ODA143",'DEVELOPERS']="Bruno Secchiari"
    df_Merge.loc[df_Merge['DEVELOPERS']=="Santiago Kitashima",'Manager']="Martin Campos"
    df_Merge.loc[df_Merge['DEVELOPERS']=="Maria Laura Bisaccia",'Manager']="Martin Campos"
    df_Merge.loc[df_Merge['DEVELOPERS']=="Ezequiel Ferlauto",'Manager']="Martin Campos"
    df_Merge.loc[df_Merge['DEVELOPERS']=="Bruno Secchiari",'Manager']="Martin Campos"

    df_Merge.to_excel(r"C:\Users\016434613\Desktop\dev over90.xlsx", index=False)

'C:\\Users\\016434613\\Downloads\\progress_dt_tasks_details_report.xlsx'

Credentials successfully created!

In [6]:
import pandas as pd
import re
import subprocess
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import os
import requests
import json
import time
import pickle
import glob
from shutil import copyfile

req = requests.get("https://w3-unifiedprofile-api.dal1a.cirrus.ibm.com/v3/016434613/teamResolved")
req.text
#dictdatos = req.json()
#devlist = dictdatos['content']['functional']['reports']

'Not Found'

In [1]:
from Create_Credentials import createCredentials

cr = createCredentials('marcamp@ar.ibm.com','MyNporsiempre2031.')
cr.create('w3id_credentials')

Credentials successfully created!